#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

# rbenv
source $OPENSHIFT_DATA_DIR/rbenv-init.sh

cd $OPENSHIFT_REPO_DIR

bundle exec unicorn -D -c config/unicorn.rb \
  -o $OPENSHIFT_INTERNAL_IP \
  -p $OPENSHIFT_INTERNAL_PORT

